#!/bin/bash
source  ./config/aws_key.sh
source  ./config/env.sh
source  ./scripts/colors.sh
cat     ./scripts/.name 

make cluster_init

# Set the context
# Kops will set your kubectl context to od.o.thinkdeep.io

# Wait until the cluster is ready
(exec ./scripts/wait_cluster.sh)

# Wait for DNS to update
(exec ./scripts/wait_dns.sh)

# Remove the old helm and install the new one
make helm_delete
make helm_init
make helm_add_repos

source <(kubectl completion zsh)
source <(helm completion zsh)

# Install Kube Dashboard and Monitoring & Get the Dashboard's password
make install_ui install_monitoring


# Wait for helm client to deploy
(exec ./scripts/wait_helm.sh)

# Install Kafka
helm install --name opendata -f component/kafka/values.yaml incubator/kafka

# Install elasticsearch
kubectl create -f component/elasticsearch/
kubectl annotate service elasticsearch dns.alpha.kubernetes.io/external=es.${DNS_ZONE}

# Scale elasticsearch
kubectl scale rc --replicas=3 es-data

cecho "Done." green 
