apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: bfs
spec:
  schedule: "15 2 * * *" 
  jobTemplate:
    spec:
      template:
        metadata:
          name: bfs
        spec:
          containers:
          - name: bfs
            image: olib10/bfs-uv-importer:v0.2
            env:
            - name: "KAFKA_HOST"
              value: "kafka.kafka:9092"
            - name: "KAFKA_TOPIC" 
              value: "bfs"
          restartPolicy: Never 
