apiVersion: batch/v1
kind: Job
metadata:
  name: bsf
spec:
  template:
    metadata:
      name: bsf
    spec:
      containers:
      - name: bsf
        image: olib10/bsf-uv-importer
        env:
        - name: "KAFKA_HOST"
          value: "kafka.kafka:9092"
        - name: "KAFKA_TOPIC" 
          value: "bsf"
      restartPolicy: Never
