apiVersion: batch/v1
kind: Job
metadata:
  name: wdi
spec:
  template:
    metadata:
      name: wdi
    spec:
      containers:
      - name: wdi
        image: ahmadjawidjami/luftdaten_info_importer
        env:
        - name: "RESOURCE_URL"
          value: "http://archive.luftdaten.info/2016-12-10/"
        - name: "KAFKA_BOOTSTRAP_SERVERS"
          value: "kafka.kafka:9092"
        - name: "KAFKA_BROKER_LIST"
          value: "kafka-0.broker.kafka.svc.cluster.local:9092"
        - name: "KAFKA_TOPIC" 
          value: "wdi"
      restartPolicy: Never
