apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: go-validator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-validator
    spec:
      containers:
      - name: go-validator
        image: tubpaul/go_consumer
        env:
          - name: "BROKER_URL"
            value: "kafka-0.broker.kafka.svc.cluster.local:9092"
          - name: "ELASTIC_URL"
            value: "http://elasticsearch:9200"
          - name: "TOPICS"
            value: "wdi"
          - name: "CONSUMER_GROUP"
            value: "wdi-group"
          - name: "BULK_LIMIT"
            value: "1000"
          - name: "DATASOURCE_ID"
            value: "wdi"
          - name: "DEBUG"
            value: "true" # "false" # "true"
          - name: "TIMEOUT_SECONDS"
            value: "10"
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
      restartPolicy: Always
